Class {
	#name : 'DummyTest',
	#superclass : 'TestCase',
	#category : 'IngSoft2-Tests',
	#package : 'IngSoft2-Tests'
}

{ #category : 'tests' }
DummyTest >> testDummy [

	self assert: Dummy new isDummy
]

{ #category : 'tests' }
DummyTest >> testDummy2 [

	self assert: Dummy new isDummy
]

{ #category : 'tests' }
DummyTest >> testDummy5 [

	self assert: Dummy new isDummy
]

{ #category : 'tests' }
DummyTest >> testDummy6 [

	self assert: Dummy new isDummy
]

{ #category : 'tests' }
DummyTest >> testDummy7 [

	self assert: Dummy new isDummy
]
